### STAGE 1: Build ###
# We label our stage as 'builder'
FROM node:12 as builder
WORKDIR /usr/src/app/
COPY package*.json ./
## Storing node modules on a separate layer will prevent unnecessary npm installs at each build
RUN npm ci
RUN npx ngcc --properties es2015 browser module main --first-only --create-ivy-entry-points
COPY . .

## Build the angular app in production mode and store the artifacts in dist folder
RUN $(npm bin)/ng build --prod --aot --output-path=dist

### STAGE 2: Setup ###
FROM nginx:1.16.0-alpine
## Copy our default nginx config
COPY nginx.conf /etc/nginx/conf.d/default.conf
## Remove default nginx website
RUN rm -rf /usr/share/nginx/html/*
## From 'builder' stage copy over the artifacts in dist folder to default nginx public folder
COPY --from=builder /usr/src/app/dist /usr/share/nginx/html
CMD ["nginx", "-g", "daemon off;"]
