# version: "3.7"

# volumes:
#   warm-shop: {}

# services:
#   app:
#     build:
#       context: ./
#       dockerfile: _fixtures/dockershell/Dockerfile
#       # args:
#       #   NODE_VERSION: 12
#       #   NPM_VERSION: 6
#       #   NESTJS_VERSION: 7
#       #   NG_VERSION: 11
#     image: warm-shop-image
#     working_dir: /app
#     depends_on:
#       - app-postgres-db
#       - dbadmin
#     volumes:
#       - ./:/app
#       - ~/.npmrc:/root/.npmrc
#       - ~/.npmrc:/home/node/.npmrc
#       - ~/.npm/:/home/node/.npm/
#     ports:
#       - "3000:3000" # backend ports
#       - "4200:4200" # frontend ports
#     environment:
#       APP_FRONTEND_DEV_PORT: 4200
#       APP_FRONTEND_URL: http://localhost:4200
#       APP_SERVICE_PORT: 3000
#       APP_SERVICE_URL: http://localhost:3000
#       #
#       APP_DB_PORT: 5432
#       APP_DB_HOST: app-postgres-db
#       APP_DB_USER: toweldryersdb
#       APP_DB_PASS: 12345678
#       APP_DB_NAME: warm_shop

#   app-postgres-db:
#     container_name: app_postgres_db
#     image: postgres:12
#     hostname: postgres-db
#     ports:
#       - "5432:5432"
#     environment:
#       PGPORT: "5432"
#       POSTGRES_DB: warm_shop
#       POSTGRES_USER: toweldryersdb
#       POSTGRES_PASSWORD: 12345678
#       PGDATA: ./data/postgres
#     volumes:
#       - warm-shop:/data/postgres
#     restart: always

#   dbadmin:
#     image: bitnami/phppgadmin
#     ports:
#       - 8079:8080
#     environment:
#       DATABASE_HOST: postgres-db
#       DATABASE_PORT_NUMBER: "5432"
#       PHP_POST_MAX_SIZE: 1024M
#       PHP_UPLOAD_MAX_FILESIZE: 1024M

version: '3.7' # specify docker-compose version

# Define the services/containers to be run
services:
  frontend: # name of the first service
    build: frontend # specify the directory of the Dockerfile
    ports:
      - "4200:4200" # specify port forewarding
    volumes:
      - ./frontend:/app

  backend: #name of the second service
    build: backend # specify the directory of the Dockerfile
    ports:
      - "3000:3000" #specify ports forwarding
    links:
      - db
  db: # name of the third service
    image: postgres # specify image to build container from
    ports:
      - "5432:5432" # specify port forwarding