version: '3.7' # specify docker-compose version

# Define the services/containers to be run
services:
  frontend:
    # name of the first service
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile # specify the directory of the Dockerfile
    restart: always
    ports:
      - "4200:4200" # specify port forewarding
    volumes:
      - ./frontend:/app

  backend:
    #name of the second service
    container_name: backend
    build:
      context: ./backend # specify the directory of the Dockerfile
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    ports:
      - "3000:3000" #specify ports forwarding
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    
  db:
    # name of the third service
    container_name: db
    image: postgres # specify image to build container from
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./db-data/:/var/lib/postgresql/data
    ports:
      - "5432:5432" # specify port forwarding
